-- rev/12-02-2024
CREATE TABLE MediaEntities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    api_id VARCHAR(255) UNIQUE,
    title VARCHAR(255),
    description TEXT,
    release_date DATE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE MediaEntities MODIFY COLUMN title VARCHAR(255);

ALTER TABLE MediaEntities MODIFY COLUMN api_id VARCHAR(255);

ALTER TABLE MediaEntities MODIFY COLUMN description TEXT(200);

ALTER TABLE MediaEntities MODIFY COLUMN release_date DATE;